version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: gestaocomercial # Nome do banco de dados
      POSTGRES_USER: postgres # Nome de usuário do banco de dados
      POSTGRES_PASSWORD: postgres # Senha do banco de dados
    ports:
      - '5432:5432' # Mapeamento de portas
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência de dados

volumes:
  postgres_data:
