module.exports = {
  size: {
    breakpoints: {
      lg: { value: '{size.sizing.1440}' },
      md: { value: '{size.sizing.720}' },
      sm: { value: '{size.sizing.480}' },
    },
    spacing: {
      auto: { value: '{size.sizing.auto}' },
      120: { value: '{size.sizing.120}' },
      96: { value: '{size.sizing.96}' },
      64: { value: '{size.sizing.64}' },
      48: { value: '{size.sizing.48}' },
      32: { value: '{size.sizing.32}' },
      16: { value: '{size.sizing.16}' },
      8: { value: '{size.sizing.8}' },
      4: { value: '{size.sizing.4}' },
      2: { value: '{size.sizing.2}' },
      1: { value: '{size.sizing.1}' },
      0: { value: '{size.sizing.0}' },
    },
    sizing: {
      auto: { value: 'auto' },
      full: { value: '100%' },
      half: { value: '50%' },
      vh: { value: '100vh' },
      vw: { value: '100vw' },
      min: { value: 'min-content' },
      max: { value: 'max-content' },
      fit: { value: 'fit-content' },
      0: { value: 0, attributes: { category: 'rem' } },
      1: { value: 1, attributes: { category: 'rem' } },
      2: { value: 2, attributes: { category: 'rem' } },
      4: { value: 4, attributes: { category: 'rem' } },
      8: { value: 8, attributes: { category: 'rem' } },
      16: { value: 16, attributes: { category: 'rem' } },
      24: { value: 24, attributes: { category: 'rem' } },
      32: { value: 32, attributes: { category: 'rem' } },
      40: { value: 40, attributes: { category: 'rem' } },
      48: { value: 48, attributes: { category: 'rem' } },
      56: { value: 56, attributes: { category: 'rem' } },
      64: { value: 64, attributes: { category: 'rem' } },
      72: { value: 72, attributes: { category: 'rem' } },
      80: { value: 80, attributes: { category: 'rem' } },
      88: { value: 88, attributes: { category: 'rem' } },
      96: { value: 96, attributes: { category: 'rem' } },
      104: { value: 104, attributes: { category: 'rem' } },
      112: { value: 112, attributes: { category: 'rem' } },
      120: { value: 120, attributes: { category: 'rem' } },
      240: { value: 240, attributes: { category: 'rem' } },
      360: { value: 360, attributes: { category: 'rem' } },
      480: { value: 480, attributes: { category: 'rem' } },
      600: { value: 600, attributes: { category: 'rem' } },
      720: { value: 720, attributes: { category: 'rem' } },
      840: { value: 840, attributes: { category: 'rem' } },
      960: { value: 960, attributes: { category: 'rem' } },
      1080: { value: 1080, attributes: { category: 'rem' } },
      1200: { value: 1200, attributes: { category: 'rem' } },
      1320: { value: 1320, attributes: { category: 'rem' } },
      1440: { value: 1440, attributes: { category: 'rem' } },
    },
  },
};
