module.exports = {
  tailwind: {
    colors: '{color}',
    width: '{size.sizing}',
    maxWidth: '{size.sizing}',
    minWidth: '{size.sizing}',
    height: '{size.sizing}',
    maxHeight: '{size.sizing}',
    minHeight: '{size.sizing}',
    inset: '{size.sizing}',
    spacing: '{size.spacing}',
    screens: '{size.breakpoints}',
    fontFamily: '{font.family}',
    letterSpacing: '{font.letterSpacing}',
    borderWidth: '{border.width}',
    fontSize: {
      '6xl': { value: ['{font.size.6xl}', '{font.lineHeight.6xl}'] },
      '5xl': { value: ['{font.size.5xl}', '{font.lineHeight.5xl}'] },
      '4xl': { value: ['{font.size.4xl}', '{font.lineHeight.4xl}'] },
      '3xl': { value: ['{font.size.3xl}', '{font.lineHeight.3xl}'] },
      '2xl': { value: ['{font.size.2xl}', '{font.lineHeight.2xl}'] },
      xl: { value: ['{font.size.xl}', '{font.lineHeight.xl}'] },
      lg: { value: ['{font.size.lg}', '{font.lineHeight.lg}'] },
      md: { value: ['{font.size.md}', '{font.lineHeight.md}'] },
      sm: { value: ['{font.size.sm}', '{font.lineHeight.sm}'] },
      xs: { value: ['{font.size.xs}', '{font.lineHeight.xs}'] },
    },
  },
};
